# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-app
  labels:
    app: spring-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-k8s-app
  template:
    metadata:
      labels:
        app: spring-k8s-app
    spec:
      containers:
      - name: spring-k8s-app
        image: spring-k8s-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
