apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-k8s-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/health
        pathType: Prefix
        backend:
          service:
            name: spring-k8s-service
            port:
              number: 80
