---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-k8s-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
subjects:
- kind: ServiceAccount
  name: spring-k8s-account
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
